//select sector
export const FETCH_SECTOR_REQUEST = "FETCH_SECTOR_REQUEST";
export const FETCH_SECTOR_SUCCESS = "FETCH_SECTOR_SUCCESS";
export const FETCH_SECTOR_ERROR = "FETCH_SECTOR_ERROR";

// user infor
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";